export interface Property {
  id: string;
  title: string;
  location: string;
  distance: string;
  dates: string;
  price: number;
  rating: number;
  images: string[];
  category: string;
  isGuestFavorite?: boolean;
  amenities: string[];
  description?: string; // Can be auto-generated by AI
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  isThinking?: boolean;
}

export enum Category {
  Icons = "Icons",
  Beachfront = "Beachfront",
  AmazingPools = "Amazing Pools",
  Cabins = "Cabins",
  Omg = "OMG!",
  Camping = "Camping",
  TinyHomes = "Tiny Homes",
  Lakefront = "Lakefront",
  Arctic = "Arctic",
}
